### ISSUE TITLE
Create an Astar replica in FV-Rococo

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos#116]
As a LAOS dev I want a Astar replica in FV-Rococo, so I can test XC-20 transfers of tokens to & from it.

ACCEPTANCE:
* I can connect with MMask to Astar@FV-Rococo
* I can use Astar@FV-Rococo to deploy/use smart contracts

**Comment by asiniscalchi** [comment]
A fork of Moonbean has been create in freeverseio. Configuration of chan specs are needed to use it in out relay chain

**Comment by ccubu** [comment]
https://github.com/freeverseio/laos-infrastructure/pull/23

**Comment by dastanfv** [comment]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fastar.gorengine.com%2Fcollator#/explorer

**Comment by ccubu** [comment]
To test rpc endpoint: 
https://astar.gorengine.com/collator
592


I deployed a test erc20 token smart contract on 0x00e249D72aAAFe56A511f0Be071e3099aB236324

**Comment by magecnion** [comment]
I can interact with the provided ERC20


![Image](https://github.com/freeverseio/laos/assets/5495235/84508fee-0e6d-4568-ad77-b0a9348aefd9)

**Comment by magecnion** [comment]
I create another ERC20 token (TrujiToken) and made some interactions: 0x851b1F9F68BC7c7E3D86E3E9E7A2218920B298bA
