### ISSUE TITLE
EVM events can be obtained via RPC-EVM! (integration test?)

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos#118]
As a DApp developer on the Evochain I want to get the events of createCollection and MintAsset by using standard web3 tools connected to the RPC endpoint, so that my DApps, which track events, can work

Note: have a look at this code that shows potential issues with current implementation: https://github.com/freeverseio/experiments/tree/master/laos_hardhat

ACCEPTANCE:
* I can use hardhat to get the events of createCollection and MintAsset
* If the events could not be queried because of a bug... **please update runtime immediately after fixing it** (hotfix), since Blackhole will be using this during their current sprint

**Comment by tonimateos** [comment]
Note: since this may end up in a hotfix, then branch from last release tag, to avoid merging code that is still developed during the sprint.

**Comment by dastanfv** [comment]
[ ] investigate evm fetch log issue
[ ] introduce integration testing suite (fork moonbeam's or frontier's)

**Comment by dastanfv** [comment]
the linked PR contains a work that can be continued to properly investigate the evm log issue and adding integration testing suite

**Comment by asiniscalchi** [comment]
Logs bugs are fixed. v0.3.2 was released and deployed in seldon.
