### ISSUE TITLE
Open XCM channel Caladan --> Astar@FVRococo

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos#121]
As a LAOS dev I want an open XCM channel Caladan -> Astar@FVRococo so that I can later develop XC-20 transfers

ACCEPTANCE:

* I can go to relaychain and query `Chain State -> hrmp -> hrmpChannels` to prove that there is a channel established between Caladan and Astar.
* I can send a ping through the channel

**Comment by dastanfv** [comment]
https://wiki.polkadot.network/docs/build-hrmp-channels#:~:text=To%20open%20a%20channel%20from,accept%20and%20do%20the%20same.

**Comment by dastanfv** [comment]
https://github.com/paritytech/polkadot-sdk/blob/master/cumulus/parachains/pallets/ping/src/lib.rs

**Comment by asiniscalchi** [comment]
for QA:


![Image](https://github.com/freeverseio/laos/assets/2387339/356edabe-e7db-4404-8f99-d6d9f531f510)

**Comment by dastanfv** [comment]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fcaladan.gorengine.com%2Fown#/explorer/query/0xa360a4737a55b89cb689ad83040070dba36b84bea89342115728e02aa882d6f4

one example of xcm call from Astar to caladan
