### ISSUE TITLE
Apply Substrate Review comments

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos#146]
As a LAOS dev, I want to make sure that the review provided by the SBP is duly taken care of, so my code is better

ACCEPTANCE:
* we apply the changes we deem necessary from the provided review

**The review test:**

Still relevant:

```
laos-ownership-node:
      - Runtime is using 60M as BlockGasLimit, it should be 15M.


It seems that `MAXIMUM_BLOCK_WEIGHT` is miscalculated:
          ```
          pub const MAXIMUM_BLOCK_WEIGHT: Weight =
            Weight::from_parts(WEIGHT_REF_TIME_PER_SECOND.saturating_mul(2), 5 * 1024 * 1024);
          -->
          pub const MAXIMUM_BLOCK_WEIGHT: Weight =
            Weight::from_parts(WEIGHT_REF_TIME_PER_SECOND.saturating_div(2), 5 * 1024 * 1024);
          ```

We'd recommend to add the "txpool" RPC methods to your collators:
            https://github.com/paritytech/frontier/blob/master/template/node/src/rpc/eth.rs#L193
```

Not relevant anymore:

       - [DONE] laos-evolution-node:
        - pallet-living-assets-evolution:
          Rename `TemplateModule` -> `LivingAssetsModule` in `[mock.rs](http://mock.rs/)` and `[tests.rs](http://tests.rs/)`

        - [DONE] Please benchmark the `pallet-living-assets-ownership`

        - [DONE as part of Unified Accounts]AccountIdToH160 and H160ToAccountId 
            WeI'd recommend to evaluate another approach such as:
                - "binding H160 to SS58 AccountId" via an extrinsic that verifies an Ethereum signature to prove that an H160 address is owned by the SS58 owner.
                That way the H160 owner would be able to sign and send transactions directly to the EVM (e.g. via MetaMask, Hardhat, etc).

laos-bridge:
        - Code looks good but as it is a bridge (with its big complexity) we'd recommend to audit (or part of) it later (no need to do it in M1).

**Comment by asiniscalchi** [comment]
![Image](https://github.com/freeverseio/laos/assets/2387339/ccf10204-baa9-43ed-8a9f-f54728eb7bb1)
