### ISSUE TITLE
Set Existential Deposit to 0

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos#165]
As a LAOS user I want the balances policy to be as close as possible to Ethereum, so my dapps there work here

Note: https://github.com/freeverseio/laos/blob/main/ownership-chain/runtime/src/lib.rs#L239

**ACCEPTANCE**:

* I can query the constant in polkadot.js and I see 0
* I see an account existing with 1e-18 DROP
* I can transfer 1e-18 DROP to an account that had no balance, and check it has 1Wei

**Comment by magecnion** [comment]
https://github.com/freeverseio/laos/assets/5495235/d8f6752f-ce27-49b6-a170-0a223511088e

**Comment by ccubu** [comment]
I was able to accomplish all three acceptance criteria


![Image](https://github.com/freeverseio/laos/assets/60666948/5acf4a47-f351-48e3-bce0-3262d71f98dd)
