### ISSUE TITLE
Newly created MinterEvolver contracts return bytecode

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos#169]
As a user of LAOS I want my web3 libraries to work well with the newly created MintEvolve contracts, so my Dapps on LAOS can work

check this link to see how we inject code in genesis: [here](https://github.com/freeverseio/laos/blob/adcfce91f39500848d75dea7d91dc58b7ddcdaf7/ownership-chain/node/src/chain_spec.rs#L162)

ACCEPTANCE:
* I can deploy a proxy-contract that calls the newly created contracts, using proxy methods, and they all work as if I were calling the newly created contracts directly. If this requires the created-contracts to return a non-null bytecode, they must return the same as 0x00...402

**Comment by asiniscalchi** [comment]
![Image](https://github.com/freeverseio/laos/assets/2387339/77074d97-2cd9-4701-85f7-64b143b43d80)
