### ISSUE TITLE
Record weights in precompiles

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos#195]
Apparently, the weights for TXs that go via the EVM precompiles report a weights that is x10 - x30 times cheaper than what it should, potentially leading to a vulnerability: include more TXs in one single block than allowed by the relay chain. Unpredictable consequences.

Please please please, do not block Caladan unless 100% necessary :-)

**ACCEPTANCE**:
* add weights in precompiles
* a new version of the runtime is produced, which equals [ v0.6.0 + fix ]

**Comment by dastanfv** [comment]
more context: #174
