### ISSUE TITLE
Review safety against Precompile attacks based on delegateCall

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos#196]
Review this issue that was discovered in Moonbeam's precompiled contracts, and make sure LAOS precompiles are safe against it:

https://medium.com/@Beosin_com/security-audit-series-what-is-a-precompiled-contract-vulnerability-5174e20e24e9

ACCEPTANCE:
* if we are vulnerable to this issue, the issue is fixed, and a test shows prev/new behaviour
* if the team considers this critical, then this is included as part of the hotfix.

**Comment by magecnion** [comment]
Delegate call performed used the following code:


![Image](https://github.com/freeverseio/laos/assets/5495235/546606d4-5078-485a-9558-4c8fb0ff286d)

Transaction reverted as expected
![Image](https://github.com/freeverseio/laos/assets/5495235/8b8d8e4b-b7af-4936-b5b3-b6188dd9708b)
