### ISSUE TITLE
Establishing a Permanent LAOS Parachain on Rococo Relay Chain

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos#248]
As a LAOS developer and stakeholder, I aim to establish and maintain a permanent LAOS parachain on the Rococo relay chain, to fully integrate and continuously leverage the advanced functionalities of the Rococo network in our blockchain operations.

### **Acceptance Criteria:**
- **Chain Naming**: Decide and finalize a unique and identifiable name for the chain.
- **Chain Synchronization**: Verify the ability to synchronize to the chain through the provided node.
- **Public Node Accessibility**: Ensure that a public node of the LAOS Rococo parachain is reachable and operational for external access in kube development cluster.
- **Parachain/Parathread Status**: Confirm that the chain is either an active parachain or a parathread in waiting, ready to be promoted by the Rococo governance.

Notes:

https://github.com/paritytech/subport/issues/new?assignees=al3mart%2CAlexD10S&labels=Rococo&projects=&template=rococo.yaml
![Image](https://github.com/freeverseio/laos/assets/43603913/6f763264-d665-4cc1-ac26-208ae14c770a)
^^ Conversation with a code parachain dev of Parity

**Comment by asiniscalchi** [comment]
https://github.com/paritytech/subport/issues/624

all done by our side ... waiting to be onboarded

**Comment by asiniscalchi** [comment]
![Image](https://github.com/freeverseio/laos/assets/2387339/a21c5f4d-0611-4da7-a880-7c64828f5adb)

**Comment by asiniscalchi** [comment]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.giedi.laosfoundation.io#/explorer

**Comment by asiniscalchi** [comment]
![Image](https://github.com/freeverseio/laos/assets/2387339/48fd8043-3aec-4acd-96c4-44a81ca254e4)

**Comment by asiniscalchi** [comment]
![Image](https://github.com/freeverseio/laos/assets/2387339/a26a7228-39b3-471f-bd06-b3d6383274be)

we were able to produce blocks by buying coretime on ROcoco ... waiting to buy it on Rococo::coretime parachain when it's operative

**Comment by asiniscalchi** [comment]
![Image](https://github.com/freeverseio/laos/assets/2387339/ef34a750-d168-45da-b8b0-57ff50ded836)


validation on Rococo is not so stable ... so this is was we got
