### ISSUE TITLE
Implement DAME - Extend claim, and get claims

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos#249]
As a user I want to extend the metadata of any NFT anywhere and see the extensions about that NFT, so I can enjoy many use cases. 

Note: Recall that if we need to hash something, we just care about its speed/cost.

**Acceptance**: 
* The new pallet is called DAME
* I can use the following methods / events, as specified in [here](https://github.com/freeverseio/laos/issues/236#issuecomment-1862959426), at a hardcoded precompile address:
```
Write:
  function extendTokenURI(string calldata uloc, string calldata tokenURI) external;
  event TokenURIExtended(address indexed claimer, string indexed uloc, string tokenURI);
Read:
  function balanceOfUL(string calldata uloc) external view returns (uint256);
  function claimerOfULByIndex(string calldata uloc, uint256 index) external view returns (address);
  function extensionOfULByIndex(string calldata uloc, uint256 index) external view returns (string memory);

```

**Comment by tonimateos** [comment]
**Important**: since a string cannot be indexed, we will follow the Solidity convention where an emitted event that has an `indexed string` actually emits an **indexed** kecak256 of that string.

So, we decided that wherever you had an event with a universal location  `string indexed ul` ==> make the event emit BOTH `string indexed hashed_ul` and `string ul`.

more info: https://discord.com/channels/771737494500802600/1107950903803256942/1195044542496383057

**Comment by ccubu** [comment]
I was able to extend a ul
![Image](https://github.com/freeverseio/laos/assets/60666948/cfd57b7d-f459-486d-8fdf-060843028cb6)

I could call all the read methods as shown here:


![Image](https://github.com/freeverseio/laos/assets/60666948/ade454d1-8651-4139-a668-019d813273ab)


Also the claimerOfUlByIndex and extensionOfUlByIndex read methods when asked for an unexisting claim for a ul they revert as specified.

balanceOfUL when asked for an unexistent claim returns 0



![Image](https://github.com/freeverseio/laos/assets/60666948/71a10440-4dcb-40da-a875-671f9378f50b)

**Comment by ccubu** [comment]
I was able to retrieve the event TokenURIExtended with this script

```
const{ Web3 }= require('web3');
const fs = require('fs');
const ownerAddress = "0xbEC56fDDd0836A4Ae234fD9aC5495E1e9E94462F" 
const ownerPrivateKey="priv-key"
async function extendTokenURI(dameContract, web3) {
    try {
        const extendMethod = await dameContract.methods.extendTokenURI("uloc-4", "tokenuri-4");

        const encodedABI = extendMethod.encodeABI();

        const tx = {
            from: ownerAddress,
            to: dameContract.options.address,
            gas: 6000000, // Set an appropriate gas limit
            gasPrice: 20000000000, // Gas price settings

            data: encodedABI
        };
    
        // Sign and send the transaction
        const signedTx = await web3.eth.accounts.signTransaction(tx, ownerPrivateKey);
        console.log("tx signed")
        const receipt = await web3.eth.sendSignedTransaction(signedTx.rawTransaction);
        
        console.log("Transaction receipt:", receipt);
    
    } catch (error) {
        console.error("An error occurred during the call:", error);
    }
}

async function main() {
    try {
        const web3 = new Web3(new Web3.providers.WebsocketProvider('ws://127.0.0.1:9999')); // Replace with your RPC URL

        const dameAbi = JSON.parse(fs.readFileSync('./artifacts/contracts/dame.sol/AssetMetadataExtender.json', 'utf8'));
        const dameAddress = "0x0000000000000000000000000000000000000404"
       
        const dameContract = new web3.eth.Contract(dameAbi.abi, dameAddress);

        dameContract.events.TokenURIExtended({}, function(error, event){ console.log(event); }).on("data", function(log){
                console.log('got data', log);
            });
       
        await extendTokenURI(dameContract, web3);
    } catch (error) {
        console.error("An error occurred:", error);
    }
}

main().catch(console.error);
```



![Image](https://github.com/freeverseio/laos/assets/60666948/3fe6a0a2-54da-4ddf-9b03-c2c1d7cc3ef7)
