### ISSUE TITLE
Implement DAME - rest of READ methods

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos#251]
As a DApp developer I want to be able to get the extension of an NFT done by a specified claimer, so I can use extensions of claimers that I care about in my DApp.

Note: Recall that if we need to hash something, we just care about its speed/cost.

**Acceptance**: I can use the following methods, as specified in [here](https://github.com/freeverseio/laos/issues/236#issuecomment-1862959426), at a hardcoded precompile address:
```
Read:
  function extensionOfULByClaimer(string calldata uloc, address claimer) external view returns (string memory);
  function hasExtensionByClaimer(string calldata uloc, address claimer) external view returns (bool);
```

**Comment by ccubu** [comment]
I was able to after extending a ul, call the given methods

![Image](https://github.com/freeverseio/laos/assets/60666948/f25b4e6c-07fa-42bd-b5e7-687613869755)

hasExtensionByClaimer returns false when asked for a ul without extension


![Image](https://github.com/freeverseio/laos/assets/60666948/7c897f9f-b97a-4e36-8f40-95da3694f92f)


and extensionOfULByClaimer reverts when asked for an unextended ul


![Image](https://github.com/freeverseio/laos/assets/60666948/2f25273e-178e-4364-96cc-33049864b677)
