### ISSUE TITLE
Ensuring `node --version` Command Reflects Accurate GitHub Tag Version

### ISSUE THREAD

**Issue by asiniscalchi** [freeverseio/laos#265]
#### **Purpose:**
To align the version output of the `node --version` command with the corresponding GitHub tag, ensuring consistency and clarity for users and developers.

#### **User Story:**
As a developer and user of our blockchain node software, I want the `node --version` command to return the exact version that matches the GitHub tag of the current release. This accuracy is crucial for tracking, debugging, and ensuring compatibility with specific versions of our software.

#### **Acceptance Criteria:**
- **Command Output Accuracy**: Ensure that the `node --version` command outputs the exact version number that corresponds to the latest GitHub tag of the node software.

![Image](https://github.com/freeverseio/laos/assets/2387339/2da919c1-ec9e-481b-87d4-f4ccec8bd170)
the image shows that all the niode we have deployed show the same (incorrect) version

**Comment by ccubu** [comment]
![Image](https://github.com/freeverseio/laos/assets/60666948/5821a623-d885-436d-a9b3-e7a94eab52b0)

last version of main built, executing the command yields wanted version result
