### ISSUE TITLE
Enable Public Minting

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos#277]
As a collection creator I want to allow others to mint on my collection, so that I can build applications and flows that use this feature.

As a LAOS stakeholder (including youtubers, ambassadors, and Freeverse) I want to let everyone bridgelessly mint assets in Ethereum paying gas fees in LAOS, not paying $200 in deploying an ERC721 in Eth, so that they can try LAOS more easily. 

ACCEPTANCE:
* the interface below works on all deployed (and newly deployed) collections via the precompiles
* the owner of the contract can continue minting
* when publicMinting is enabled, everyone can mint, but not evolve (only owner can evolve)

```

    function enablePublicMinting() external; 
    function disablePublicMinting() external; 
    function isPublicMintingEnabled() external view returns(bool);

    event enabledPublicMinting();
    event disabledPublicMinting();
```

**Comment by ccubu** [comment]
Call to isPublicMintingEnabled after disabling it:
![Image](https://github.com/freeverseio/laos/assets/60666948/f9567937-d7e3-4334-a0b0-f01db1c3b5cc)

Call to isPublicMintingEnabled after enabling it:


![Image](https://github.com/freeverseio/laos/assets/60666948/860a3ddf-38c8-4344-ad44-dd75b092b0b7)

The owner of the collection can mint and evolve as before no matter if public minting is enabled or disabled.


![Image](https://github.com/freeverseio/laos/assets/60666948/bb11a9b1-c68d-43eb-ade5-19484d48e230)

Not owners of the collection can't call enable/disable public minting:


![Image](https://github.com/freeverseio/laos/assets/60666948/2f8670aa-381a-4f4e-a95a-b40d59690b24)


With public minting enabled, not owners can mint but not evolve:


![Image](https://github.com/freeverseio/laos/assets/60666948/bba1e56d-e7b7-467b-85f0-a2402adcd19f)
