### ISSUE TITLE
Polkadot-js support with `laos-parachain` spec name

### ISSUE THREAD

**Issue by dastanfv** [freeverseio/laos#30]
after we switched to unified accounts, we lost support to Polkadot-js. As a workaround, we changed `spec_name` to `frontier-template` so that Polkadot.js recognizes our chain as an ethereum chain.

Polkadot.js has a hard-coded list of ethereum chain runtime names, and based on that they enable `ecdsa` signatures and `H160` accounts.

We have to make a PR to them to add our chain in that list.

**Comment by magecnion** [comment]
tackled here #314
