### ISSUE TITLE
Correct DAME method names

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos#300]
```
    function extendTokenURI  -->  extendULWithExternalURI
    function updateExtendedTokenURI  -->  updateExtendedULWithExternalURI
    event TokenURIExtended  -->  extendedULWithExternalURI
    event ExtendedTokenURIUpdated  -->  updatedExtendedULWithExternalURI

also, please let's unify in this interface, and use the same convention for all input params, so that they all start with an underscore "_"

```

**ACCEPTANCE**
* the methods & events are changed as described above
* input params are unified: we use the same convention for all input params, so that they all start with an underscore 
* precompiled contract address is a new one
* release of new node
* this is made as hotfix to v0.10.0
* we upgrade Caladan, and we upgrade KLAOS, ideally before Friday

**Comment by magecnion** [comment]
Make QA in Caladan before upgrade runtime in KLAOS

**Comment by asiniscalchi** [comment]
![Image](https://github.com/freeverseio/laos/assets/2387339/93e39cc2-629f-4ced-93be-0e22ae74f73a)
