### ISSUE TITLE
Implement session related traits for `ParachainStaking`

### ISSUE THREAD

**Issue by dastanfv** [freeverseio/laos#309]
Once #308 is done, we need to implement `SessionManager`, `EndSession` and `EstimateNextSession` traits for the `Pallet<T>`, so that `ParachainStaking` is responsible for selecting collators and generally managing the session.

`ParachainStaking` already implements the logic of selecting top candidates for block production.

For reference: 
* https://github.com/KILTprotocol/kilt-node/blob/develop/pallets/parachain-staking/src/lib.rs#L2503
* https://github.com/Polimec/polimec-node/tree/main/pallets/parachain-staking

**ACCEPTANCE**

- Anyone is able to stake on a collator using polkadot.js
- Block producers are selected according to their stake (implicit in this: Above mentioned traits are implemented)

**Comment by ccubu** [comment]
Could not transfer frozen token from a collator:
![Image](https://github.com/freeverseio/laos/assets/60666948/50ee96f1-8ce6-4a2a-b048-726a131f3708)

2 collators with same stake:


![Image](https://github.com/freeverseio/laos/assets/60666948/cb4d8002-3ec2-4c7a-966d-a9be2b3f379f)

joined a 3rd collator with staking:


![Image](https://github.com/freeverseio/laos/assets/60666948/5bf27037-b775-421d-b6cb-49c39dcf3326)



3 stakers ownership 1 & 2 with 10k and ownership 0 with 5k:


![Image](https://github.com/freeverseio/laos/assets/60666948/10d2c8fa-78fa-4afa-a824-ba1062f29461)


Delegate to 5k to last staker
![Image](https://github.com/freeverseio/laos/assets/60666948/12db6779-485a-4463-8b79-da9ce00948c5)



Claimed delegator reward:


![Image](https://github.com/freeverseio/laos/assets/60666948/40a7db6d-9f90-4e8b-bc64-afee7aaa2568)
