### ISSUE TITLE
Integrate `fast-runtime` feature

### ISSUE THREAD

**Issue by dastanfv** [freeverseio/laos#324]
Integrate `fast-runtime` feature to override session, epoch values for testing environment.
https://github.com/paritytech/polkadot-sdk/blob/master/polkadot/runtime/common/src/lib.rs#L249

**ACCEPTANCE**
- time config values are different based on env: prod or testing
- time config values in testing env is fast, i.e easy to notice and test

**Comment by asiniscalchi** [comment]
https://substrate.stackexchange.com/questions/9466/way-to-force-a-new-session-when-using-pallet-session ?

**Comment by asiniscalchi** [comment]
https://github.com/AcalaNetwork/Acala/tree/27a6d5ac1f7481bb4e16b1ea697db7b8e2210c8c/modules/session-manager
