### ISSUE TITLE
Polimec's Governance Genesis Case Study

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos#343]
As a LAOS stakeholder I want to analyse Polimec's governance genesis config so that LAOS launches as securely as possible.

**ACCEPTANCE**:
* We discuss internally their decision and add user stories if needed

**Comment by asiniscalchi** [comment]
![Image](https://github.com/freeverseio/laos/assets/2387339/bba8f260-a322-426b-bbe3-380e2175f749)

**Comment by tonimateos** [comment]
https://polimec.medium.com/road-to-launch-0057cc345d6c

**Comment by magecnion** [comment]
We decided to go with sudo at genesis, then we will implement governance at some point.
