### ISSUE TITLE
Make token non-transferable

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos#349]
**As a** LAOS stakeholder,  
**I want** to make sure that the token is not transferable (unless done by governance) until governance decides otherwise,  
**So that** I can go through a public sale without previous trading of the token.

### **Acceptance Criteria:**

1. **Governance-Only Transfers:** : I cannot transfer any token on my own. Only explicitly authorized transfers by governance can take place, ensuring no premature distribution or trading of tokens.
2. **Programmatic Exemptions for Rewards:**:  Automatic transfers from the RewardsAccount to collators are allowed. These transfers are essential for the ongoing incentivization of collators who support the network by producing blocks.

### **Notes:**

- This restriction is intended to maintain the integrity and value of the token during the public sale phase.
- Governance will review and decide on the appropriate time and conditions under which the token will become fully transferable.
- This approach ensures a controlled distribution environment, aligning with the strategic goals of the LAOS for its token economy.

**Comment by asiniscalchi** [comment]
Note: there is a pallet provided by substrate that does it via allow/disallow lists:
https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/tx-pause/src/lib.rs
https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/safe-mode/src/lib.rs

**Comment by asiniscalchi** [comment]
Polimec does the following:
```rust
pub struct BaseCallFilter;
impl Contains<RuntimeCall> for BaseCallFilter {
	fn contains(c: &RuntimeCall) -> bool {
		use pallet_balances::Call::*;
		use pallet_vesting::Call::*;

		match c {
			// Transferability lock.
			RuntimeCall::Balances(inner_call) => match inner_call {
				transfer { .. } => false,
				transfer_all { .. } => false,
				transfer_keep_alive { .. } => false,
				transfer_allow_death { .. } => false,
				_ => true,
			},
			RuntimeCall::Vesting(inner_call) => match inner_call {
				// Vested transfes are not allowed.
				vested_transfer { .. } => false,
				_ => true,
			},
			_ => true,
		}
	}
}
```
