### ISSUE TITLE
Disclaimer from node command line must be correct

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos#377]
Fix the link. Ideally, it points to a file in our own LAOS repository, so we don't depend on others.

It must be this file: https://livingassets.s3.amazonaws.com/website_legal/token_disclaimer.pdf

**Comment by dastanfv** [comment]
![Image](https://github.com/freeverseio/laos/assets/137785454/a6194893-7825-422c-ac93-7c6b79b5e807)
