### ISSUE TITLE
Update `spec_name` to "klaos" for Runtime Distinction

### ISSUE THREAD

**Issue by asiniscalchi** [freeverseio/laos#381]
# Update `spec_name` to "klaos" for Runtime Distinction

**As a** KLAOS blockchain developer,  
**I want** to change the `spec_name` of klaos runtime to "klaos",  
**So that** it is clearly distinguished from the "laos" runtime when users and developers interact with klaos blockchain through various interfaces, including polkadot.js.

## Acceptance Criteria:
1. **Change Implementation:** The `spec_name` in the klaos runtime configuration is updated from "laos" to "klaos", ensuring that this change does not adversely affect any existing functionalities or configurations, other than altering the name.

2. **Clear Distinction in Interfaces:** Upon updating the `spec_name`, interfaces such as polkadot.js must clearly display "klaos/version" in all areas where the klaos runtime version is shown, ensuring that it is distinct from "laos/version" and easily identifiable by users and developers.

![Image](https://github.com/freeverseio/laos/assets/2387339/bcee8998-2314-4b9b-8a17-85632df50a2f)

![Image](https://github.com/freeverseio/laos/assets/2387339/b7ec086b-9bb7-4016-9c44-a9931ec38709)

**Comment by ccubu** [comment]
Screenshot from launching zombienet with klaos



![Image](https://github.com/freeverseio/laos/assets/60666948/1cf7eb2b-4c21-4cc5-b285-c05e006b6e9b)
