### ISSUE TITLE
Strategic Token Allocation for Genesis Launch and Governance Empowerment

### ISSUE THREAD

**Issue by asiniscalchi** [freeverseio/laos#399]
## User Story

**As a** member of the LAOS blockchain community,  
**I want** the governance to retain control of the majority of tokens at genesis, with a designated amount for initial block producers and a substantial portion in the RewardsAccount,  
**so that** we can ensure a stable launch with empowered governance and incentivized block producers.

## Acceptance Criteria

1. **Token Distribution**: At genesis, the total token supply will be 1 billion tokens. 
2. **Initial Block Producers Stake**: The two initial block producers will be allocated a portion of these tokens for staking purposes to secure their commitment and participation from the start.
3. **RewardsAccount Funding**: 150 million tokens will be allocated to the RewardsAccount ( no pvk ), which is dedicated to remunerating the block producers.
4. **Governance Holdings**: The remaining tokens will be held by the governance.
5. **Governance Identity**: set to "0xd16D70A63580c15EEAD7145f0f03A41c94027e63"

**Comment by asiniscalchi** [comment]
0xffffffffffffffffffffffffffffffffffffff01 is the account of the collator rewards

**Comment by ccubu** [comment]
The balances distribution seems to be correct on genesis:

![Image](https://github.com/freeverseio/laos/assets/60666948/1bd8801b-fdf1-428b-bc3a-f3b56c5f592b)
