### ISSUE TITLE
Calculate Runtime Weights

### ISSUE THREAD

**Issue by asiniscalchi** [freeverseio/laos#435]
**As a** blockchain developer,  
**I want** the weights of the runtime to be accurately calculated and documented,  
**So that** we can ensure our blockchain operates efficiently, balancing resource consumption with performance, and maintains compatibility with the overarching network requirements.

## Acceptance Criteria:

- **1:** Review and understand the current runtime logic and operations that require weight calculations, including transactions, smart contracts, and any other relevant runtime functions.
- **2:** Implement or utilize existing benchmarking tools to measure the computational and storage resources used by each runtime operation. This process should cover a comprehensive range of possible scenarios to ensure accurate weight determination.
- **3:** Based on the benchmarking data, calculate the weights for each runtime operation. These weights should reflect the real-world resource usage as closely as possible.
- **4:** Integrate these calculated weights into the runtime, ensuring that they are used to limit and meter the resource consumption of blockchain transactions and operations.

link: https://github.com/paritytech/polkadot-sdk/blob/master/substrate/scripts/run_all_benchmarks.sh
or: https://github.com/moonbeam-foundation/moonbeam/blob/master/scripts/run-benches-for-runtime.sh

**Comment by dastanfv** [comment]
end result should look sth like this: 
https://github.com/moonbeam-foundation/moonbeam/tree/master/runtime/common/src/weights

**Comment by dastanfv** [comment]
I started working on it, but my machine doesn't satisfy reference machine [requirements](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/utils/frame/benchmarking-cli/src/machine/README.md?plain=1) for benchmarking.

here is the output:

```bash
./target/release/laos benchmark machine --chain dev
2024-03-27 17:10:03 Running machine benchmarks...    
2024-03-27 17:10:29 
+----------+----------------+-------------+-------------+-------------------+
| Category | Function       | Score       | Minimum     | Result            |
+===========================================================================+
| CPU      | BLAKE2-256     | 982.79 MiBs | 783.27 MiBs | ✅ Pass (125.5 %) |
|----------+----------------+-------------+-------------+-------------------|
| CPU      | SR25519-Verify | 813.58 KiBs | 560.67 KiBs | ✅ Pass (145.1 %) |
|----------+----------------+-------------+-------------+-------------------|
| Memory   | Copy           | 36.31 GiBs  | 11.49 GiBs  | ✅ Pass (315.9 %) |
|----------+----------------+-------------+-------------+-------------------|
| Disk     | Seq Write      | 3.25 GiBs   | 950.00 MiBs | ✅ Pass (350.5 %) |
|----------+----------------+-------------+-------------+-------------------|
| Disk     | Rnd Write      | 339.27 MiBs | 420.00 MiBs | ❌ Fail ( 80.8 %) |
+----------+----------------+-------------+-------------+-------------------+
From 5 benchmarks in total, 4 passed and 1 failed (10% fault tolerance).    
2024-03-27 17:10:29 The hardware fails to meet the requirements    
2024-03-27 17:10:29 Failing since --allow-fail is not set 
```

**Comment by dastanfv** [comment]
2 temporary fixes/mitigations come to my mind about `balances` benchmarks:

1. Conditional non-zero ED, i.e under `#[cfg(feature = "runtime-benchmarks")]`
2. Open an issue in `polkadot-sdk`. They enable setting ED to 0, with `insecure_zero_ed` feature, so it should be possible to also have benchmarks that run properly with ED 0

**Comment by asiniscalchi** [comment]
it might be the solution and also it's a contribution to the polkadot-sdk
