### ISSUE TITLE
Restricting EVM Transactions to Balance Viewing Only

### ISSUE THREAD

**Issue by asiniscalchi** [freeverseio/laos#437]
**As a** blockchain governance member,  
**I want** the EVM to be restricted to only allow balance viewing,  
**So that** we can ensure a secure and controlled start of the network, with all EVM transactions other than balance inquiries explicitly disallowed.

## Acceptance Criteria

1. **Genesis Block Configuration**: Configure the EVM pallet within the genesis block to restrict functionality to balance inquiries only. This setup should prevent the execution of any transactions, smart contract deployments, or other EVM-related activities except for viewing account balances.

**Comment by asiniscalchi** [comment]
we won't user to be able to use the EVM and precompiled at genesis

**Comment by ccubu** [comment]
![Image](https://github.com/freeverseio/laos/assets/60666948/3f29e13a-d1b8-48e4-86f9-4a54ce422b2e)
