### ISSUE TITLE
Launching the Laos Testing Network with Runtime v0.13.0

### ISSUE THREAD

**Issue by asiniscalchi** [freeverseio/laos#439]
**As a** blockchain network developer,  
**I want** to launch the Laos Testing Network with the updated runtime version v0.13.0,  
**So that** we can test new features, improvements, and fixes in a controlled environment before the LAOS genesis event.

## Acceptance Criteria

1. **Public Access**: Set up the Laos Testing Network infrastructure, and a public node.

**Comment by ccubu** [comment]
https://github.com/freeverseio/laos-infrastructure/pull/76
