### ISSUE TITLE
update KLAOS to klaos-runtime v0.12.1

### ISSUE THREAD

**Issue by asiniscalchi** [freeverseio/laos#440]

**Comment by tonimateos** [comment]
TX submited. Multisig needs to approve 0x7caf21381ac5e8c355cd604501df034720c4ff9509f74869a697e4080d7bb954

**Comment by asiniscalchi** [comment]
tx was send at 

![Image](https://github.com/freeverseio/laos/assets/2387339/6515b32d-4a54-4b77-86e4-5b6a0f8d5d81)
