### ISSUE TITLE
ParaId acquisition for LAOS

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos#493]
As anyone integrating LAOS (e.g. Talisman, Bifrost) I need to know LAOS ParaID, so I can integrate it.

**ACCEPTANCE**:
* A ParaID in Polkadot is obtained and controlled by the a pure-proxy controlled by the sudo multisig of the LAOS Foundation
* ParaID is added to the README

**Comment by tonimateos** [comment]
![Image](https://github.com/freeverseio/laos/assets/43603913/abe939b6-9a5c-4648-b350-d77387229bb3)

**Comment by tonimateos** [comment]
![Image](https://github.com/freeverseio/laos/assets/43603913/fed5a310-3bbb-45ef-a1a3-c0bf97e1d580)

**Comment by asiniscalchi** [comment]
![Image](https://github.com/freeverseio/laos/assets/2387339/564117a3-18f5-475e-9c82-60e8959f72a7)

paraID 3370
