### ISSUE TITLE
Set up first Freeverse staker

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos#554]
**doubt**: can a staker be created with locked tokens, or is there a minimum of unlocked tokens required ?
* part of the task is to force the decision about vesting conditions with the LAOS foundation & FV
* force to decide if we also include one FV board member (or more)

**ACCEPTANCE**
* must be controlled by the FV multisig (as opposed to LAOS Foundation), via PureProxy. 
* the staker owns funds with the same vesting conditions that will have in LAOS
* the staker is producing blocks
* a feature request/bug is reported in Polkadot.js repo

**Comment by ccubu** [comment]
https://github.com/freeverseio/LAOSOdissey/pull/13

**Comment by ccubu** [comment]
https://github.com/freeverseio/laos-infrastructure/pull/85

**Comment by ccubu** [comment]
![Image](https://github.com/freeverseio/laos/assets/60666948/0c460976-85aa-42ae-9d33-410dd15ec968)

**Comment by asiniscalchi** [comment]
issue was open in polkadot.js app repo: https://github.com/polkadot-js/apps/issues/10615

**Comment by asiniscalchi** [comment]
![Image](https://github.com/freeverseio/laos/assets/2387339/8b0801cb-32ec-418a-9f82-f44c1100c74d)
