### ISSUE TITLE
Fix issue revealed by clippy related to deprecated trait

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos#595]
As a dev I want the CI tests to be in green

Place to start finding about this isue:
https://github.com/moonbeam-foundation/moonbeam/blob/26a88a553563647992f39fbd1cce3d45a363e991/runtime/moonbeam/src/lib.rs#L1585-L1614

**Comment by ccubu** [comment]
https://github.com/moonbeam-foundation/moonbeam/blob/26a88a553563647992f39fbd1cce3d45a363e991/runtime/moonbeam/src/lib.rs#L1585-L1614

https://github.com/moonbeam-foundation/moonbeam/blob/26a88a553563647992f39fbd1cce3d45a363e991/runtime/moonbeam/src/lib.rs#L1585-L1614

future reference links extracted from this pr: https://github.com/freeverseio/laos/pull/594/files

**Comment by asiniscalchi** [comment]
Ok we have tome till September 2024 .. I suggest to wait for the other parachains to take action.
https://paritytech.github.io/polkadot-sdk/master/cumulus_pallet_parachain_system/trait.CheckInherents.html
