### ISSUE TITLE
H160 type in mint-to

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos#6]
As an initial owner of an asset in LAOS I want the tokenId in ownchain and evochain to match, so I can transfer assets in the ownership chain that have exactly the same tokenId as the one I received as initial owner in the evochain

There's a bug in concat operation.

ACCEPTANCE
* the 'to' param of mint is an H160 account
* the tokenId generated is a U256 type matching that of the ownchain, for any given (initOwner, slot) pair

**Comment by tonimateos** [comment]
Recall:

Evochain:

Now:

- owner OF COLLECTION = H256 account (they can do stuff in the evochain)
- init owner of an asset = H160 not related to the TO param provided, which is H256 TO param (this owner can do NOTHING in the evochain), it can do stuff in the OWNchain

Change proposed:

- owner OF COLLECTION = H256 account (they can do stuff in the evochain)
- init owner of an asset = H160 that matches to TO H160 provided param (this owner can do NOTHING in the evochain), it can do stuff in the OWNchain

**Comment by magecnion** [comment]
![Image](https://github.com/freeverseio/laos/assets/5495235/46c5fbe0-5f9c-497c-9526-8787573b15f0)

2923003274661805836407369665432566039311865085953 == 0x20000000000000000000000000000000000000001
