### ISSUE TITLE
New Evochain spawned with Unified Accounts

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos#61]
As a Universal Node builder I want full EVM access to the Evochain so I use my well-known EVM-compatible libraries and my life is easier.

Name: Seldon (after Hari Seldon)

ACCEPTANCE:
* I can connect with Polkadot.js to the new chain LOCALLY
* I can transfer funds using ETH addresses, using both Metamask and Polkadot.js LOCALLY

Not included:
* deploy of the new chain
* lightclient

**Comment by asiniscalchi** [comment]
Bridge is deactivated ... please reactivate the compilation + CI
