### ISSUE TITLE
Vesting precompile

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos#615]
As an EVM-only user (with MMask, etc.) I want to be able to vest my funds, so I can transfer later, using only EVM tooling.

**ACCEPTANCE**:
* Write: I can vest my tokens using an EVM library (remix or hardhat or blockscout), I can vest others' tokens (vest, vestOther)
* Read: I can query the info about my vesting using an EVM library (exactly same info I can query from substrate side)
* No need to emit evens in the EVM side

Note: you can test by doing a vestedTransfer with schedule in the past

**Comment by asiniscalchi** [comment]
![Image](https://github.com/user-attachments/assets/1fa7bc81-f6bd-4afe-9f50-3b09c0869b00)
