### ISSUE TITLE
XCM allows for Sending and Receiving MERC Tokens to/from AssetHub in Zombienet

### ISSUE THREAD

**Issue by asiniscalchi** [freeverseio/laos#709]
As a developer, I want to configure XCM to enable sending and receiving LAOS zombienet tokens.

### Description
To facilitate cross-chain transfers of LAOS zombienet tokens, we need to configure Cross-Consensus Messaging (XCM).This will allow MERC tokens to be seamlessly sent and received across chains.

### Acceptance Criteria
1. **Message Format and Protocols**
   - Define the message formats for MERC token transfers.
   - Implement the necessary protocols to handle these messages correctly.
   - I can send MERC to AssetHub and bring the tokens back to LAOS in Zombienet

2. **Testing**
   - Create automatic end-to-end testing of MERC token transfers via XCM by CI. ( Moonwall, xcm simulator, chopstick ).

**Comment by luispdm** [comment]
Useful resource: https://wiki.polkadot.network/docs/learn-assets

**Comment by asiniscalchi** [comment]
https://substrate.stackexchange.com/questions/11948/can-asset-hub-utilize-non-dot-sufficient-asset-for-paying-xcm-fee
