### ISSUE TITLE
Ensure E2E Tests are Executed on Release Branches

### ISSUE THREAD

**Issue by asiniscalchi** [freeverseio/laos#725]
**As a** DevOps Engineer  
**I want** E2E tests to be executed automatically on release branches, just as they are on the main branch  
**So that** we can ensure the stability and quality of our releases before they go live

### Acceptance Criteria:
- E2E tests are triggered automatically whenever a new commit is pushed to any release branch.

**Comment by ccubu** [comment]
Tried it in my own laos fork, and it triggers properly.
