### ISSUE TITLE
Upgrade LAOS Node for hardfork

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos#760]
We have to upgrade the nodes of LAOS to the v0.20.0: it support the hardfork happening runtime-2000+ .

ACCEPTANCE:
* These nodes run v0.20.0: collators LF, FV, bootnodes
* Repository is updated

**Comment by asiniscalchi** [comment]
![Image](https://github.com/user-attachments/assets/2d6533f4-4765-483e-b2bc-cfa7bfb67b9a)

don't have access to the k8s in Mumby and US

**Comment by asiniscalchi** [comment]
![Image](https://github.com/user-attachments/assets/d7455c48-c8e1-4f9b-bd2d-628cb936e83b)
