### ISSUE TITLE
Fix Metadata issue via runtime upgrade

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos#819]
**ACCEPTANCE:**
* I can fully operate LAOS with the latest version of polkadot.js
* Done via a hotfix to version 2200 - test on Sigma
* Mainnet is upgraded too via Tech Committee, for the task to be considered

**Comment by asiniscalchi** [comment]
https://github.com/polkadot-js/apps/issues/10954

**Comment by asiniscalchi** [comment]
fix https://github.com/polkadot-js/apps/issues/10954
