### ISSUE TITLE
Configure Election Imbalance to Treasury

### ISSUE THREAD

**Issue by asiniscalchi** [freeverseio/laos#837]
As a developer, I want to configure the elections phragmen pallet to send imbalances of kicked members to the treasury for better resource management.

   > *"The imbalance of a kicked member could go to the treasury. Bear in mind this configuration item is currently unused in the pallet."*

**Comment by ccubu** [comment]
![Image](https://github.com/user-attachments/assets/a2978882-c582-4d84-8b96-e48e9f22ceef)
