### ISSUE TITLE
Include Council in Preimage Pallet’s ManagerOrigin

### ISSUE THREAD

**Issue by asiniscalchi** [freeverseio/laos#839]
As a developer, I want to update the preimage pallet to include the council in ManagerOrigin to ensure proper governance management.

   > *"The ManagerOrigin could also include a portion of the council."*

**Comment by asiniscalchi** [comment]
[source](https://paritytech.github.io/polkadot-sdk/master/src/pallet_preimage/lib.rs.html#124)
type [ManagerOrigin](https://paritytech.github.io/polkadot-sdk/master/pallet_preimage/pallet/trait.Config.html#associatedtype.ManagerOrigin): EnsureOrigin<Self::RuntimeOrigin>
An origin that can request a preimage be placed on-chain without a deposit or fee, or manage existing preimages.

**Comment by ccubu** [comment]
![Image](https://github.com/user-attachments/assets/cb2c5dcd-df82-4bb3-afb5-759f375e38a5)
