### ISSUE TITLE
Automate Runtime build + upload

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos#92]
As a dev I want to automate runtime building + uploading compiled runtime (token, etc.) so the flow reduces human error possibilities, and save time.

Note: [sr-tool](https://github.com/paritytech/srtool) is used for production, to deterministically generate a wasm from a binary (used to check which binary generated a given wasm). Otherwise, just with a standard build, wasm files differ.

_srtool especially allows building WASM runtimes in a deterministic way, allowing CIs and users, with various machines and OS, to produce a strictly identical WASM runtime._

ACCEPTANCE:
* on each runtime release CI/CD publishes the runtime in github

Not part of the acceptance criteria: if the team sees value in using srtool, it is integrated in the automation

**Comment by ccubu** [comment]
A way of testing this can be by creating a dummy release
